### ISSUE TITLE
Fibonacci is not to be solved in a new way

### ISSUE THREAD

**Issue by asarfraaz** [ChandraBChoudhary/PythonLearningChand#1]
The question mentions to **modify** existing code.

But, in 7a10d60d194665b595b0e3363657c3733d42cc8e , you are solving it in a new way.

This will certainly help in learning a new way to print Fibonacci series, but not how to modify existing code to cater to the new requirement.

**Comment by ChandraBChoudhary** [comment]
I understand Sarfaraaz. I will redo the assignment.
Actually I wrote this fibo code before we did it in the session. So I
modified that itself.
I will redo the assignment and let you know.

Thank you

Regards,
Chandra B

**Comment by asarfraaz** [comment]
Ok 👍

**Comment by ChandraBChoudhary** [comment]
Thanks a lot.

**Comment by ChandraBChoudhary** [comment]
Hi Sarfraaz, can you take a look at my resubmitted assignment on Fibonacci , it's suffixed as Redo 

Thank you
